---
base-job: &base-job
  max_in_flight: 1

resources:
- name: repo.git
  type: git
  icon: git
  source:
    uri: git@github.com:Esysc/hello.git
    private_key: ((concourse_janus_ssh_key))
    branch: ((branch))


####################################################################################################

jobs:

- name: build-macos-12.0-m1
  <<: *base-job
  plan:
  - in_parallel:
    - get: repo.git
  - task: build-macos-12.0-m1
    file: repo.git/ci/tasks/build-macos.yml
    tags: [monterey-arm64]

- name: unit-macos-12.0-m1
  <<: *base-job
  plan:
    - get: build-dir
  - task: unit-test-macos-12.0
    tags: [monterey-tester-arm64]
    file: repo.git/ci/tasks/test-macos.yml
  